# run as:
#   docker build -f Dockerfile -t csi .

# base everything on a recent Ubuntu
FROM debian:latest

# get system packages up to date then install a basic scientific python
# note the prerequisites for scipy updating - liblapack-dev and gfortran
RUN apt-get update && apt-get -y upgrade && \
    apt-get -y install python3 python3-numpy python3-scipy python3-setuptools liblapack-dev gfortran

# set up pip, as GPy is pip distributed. for some reason python3-pip needs to be easy_install3ed
RUN easy_install3 pip
RUN pip install GPy