# run as:
#   docker build -f Dockerfile-online -t wigwams .
# (make sure there's nothing else in the directory or it will get sponged for some reason)

# base everything on a recent Ubuntu
FROM debian:latest

# get system packages up to date then install a basic scientific python
RUN apt-get update && apt-get -y upgrade && \
    apt-get -y install python3 \
         python3-numpy python3-scipy python3-pandas python3-matplotlib python3-seaborn \
         ttf-bitstream-vera
# also setup wget to get the code
RUN apt-get -y install wget
RUN apt-get -y install unzip

# add and configure our code
RUN wget https://github.com/ktpolanski/ip2/archive/master.zip
RUN unzip master.zip
RUN mv /ip2-master/wigwams/wigwams.py /wigwams
RUN mv /ip2-master/wigwams/wigwams_wrapper.py /wigwams
RUN rm master.zip
RUN rm -r ip2-master

# set the actual working directory (where the docker virtual machine will be) to where the data comes in
WORKDIR /agave

MAINTAINER Krzysztof Polanski <k.t.polanski@warwick.ac.uk>

# so this is what is going to run by default when you trigger this, in the virtual machine
# call the wigwams wrapper from the other directory while staying in /agave with the files
ENTRYPOINT ["python3", "../wigwams/wigwams_wrapper.py"]

# this is for communicating with the exterior, this is where it expects to get data
VOLUME ["/agave"]

# if nothing else is specified in the docker call, just run --help
CMD ["--help"]